name: Build - Bump Version Number

on:
  workflow_dispatch:
      
env:
  version_file: "Version.xcconfig"

jobs:
  BumpAndTag:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Find version, build number and update
        run: |
          # Find build number and increment
          CURRENT_PROJECT_VERSION=$(grep -w "CURRENT_PROJECT_VERSION" "${{ env.version_file }}" | cut -d'=' -f2 | tr -d ' ')
          ((CURRENT_PROJECT_VERSION+=1))
          sed -i '' "s/\(CURRENT_PROJECT_VERSION *= *\).*/\1$CURRENT_PROJECT_VERSION/" "${{ env.version_file }}"

          # Find version number
          MARKETING_VERSION=$(grep -w "MARKETING_VERSION" "${{ env.version_file }}" | cut -d'=' -f2 | tr -d ' ')

          # Create new full version number
          NEW_TAG="v$MARKETING_VERSION+$CURRENT_PROJECT_VERSION"

          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$CURRENT_PROJECT_VERSION" >> $GITHUB_ENV
          
      - name: Commit build number
        run: |
          git add "${{ env.version_file }}"
          git commit -m "bump: Build Number to: ${{ env.NEW_TAG }} [skip ci]" || echo "No changes to commit"
          git push
          
      - name: Create tag
        run: |
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}
          
      outputs:
        NEW_TAG: ${{ env.NEW_TAG }}
        BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
          
  CreateChangelogAndRelease:
    needs: BumpAndTag
    uses: ./.github/workflows/build-create-release.yml
    secrets: inherit
    with:
      tag_name: ${{ needs.BumpAndTag.outputs.NEW_TAG }}
      build_number: ${{ needs.BumpAndTag.outputs.BUILD_NUMBER }}