name: Clean up old workflow files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 12 1 * ?' # Every month on the 1st, at noon, UTC time
  
concurrency:
  group: "${{ github.ref }}_cleanup"
  cancel-in-progress: true
    
jobs:
  cleanup:
    name: Clean up Workflows
    runs-on: [self-hosted, Linux]
    timeout-minutes: 5
    steps:

      - name: Delete old workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: ${{ github.repository }}                   
          older-than-seconds: 259200 # 3 days
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}