name: Swift Lint

on:
  push:
    paths:
      - '.github/workflows/lint.yml'
      - '.lint.yml'
      - '**/*.swift'

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      swift: ${{ steps.changes.outputs.ts }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          echo "::set-output name=ts::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .swift$ | xargs)"
  
  SwiftLint:
    runs-on: ubuntu-latest
    needs: changedfiles
    timeout-minutes: 1
    if: ${{needs.changedfiles.outputs.swift}}
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        
#       - name: Install Swift lint
#         run: |
#             brew install swiftlint

      - name: Lint
        run: |
            swiftlint ${{needs.changedfiles.outputs.ts}}
            